export const custLoanDetails = [
    {
		rowId: 'primary1',
        label1: 'Customer Legal Name',
        data1: 'Sri Rama',           
        label2: 'Inquire Date Time',
        data2: 'Tuesday, December 19,2023',
    },
    {
        rowId: 'primary2',
        label1: 'Loan Alias',
        data1: '610226001',           
        label2: 'Current Balance',
        data2: '$23,152.54',
    },
    {
        rowId: 'primary3',
        label1: 'All-In Rate',
        data1: '11.11%',           
        label2: 'CProjected Loan Maturity Date',
        data2: '45108',
    },
    {
       rowId: 'primary4',
        label1: 'Loan Maturity Date',
        data1: 'Saturday, July 1, 2023',           
        label2: 'Available to Draw',
        data2: '$51847.46',
    },
    {
        rowId: 'primary5',
        label1: 'Est # of Payments Remaining',
        data1: '$455,646',           
        label2: 'Repricing Date',
        data2: 'Saturday, July 1, 2023',
    },
    {
       rowId: 'primary6',
        label1: 'Loan Frequency',
        data1: 'Annually',           
        label2: 'Performing Status',
        data2: 'ACCR',
    },
    {
        rowId: 'primary7',
        label1: 'Accrued Interest',
        data1: '$1,063.68',           
        label2: 'Facility Type',
        data2: 'Revol',
    },
    {
        rowId: 'primary8',
        label1: 'Other Borrowers',
        data1: 'DUCOTE TAMMY 001-7519',           
        label2: 'Facility Original Commitment',
        data2: '$75,000.00',
    },
    {
        rowId: 'primary9',
        label1: 'Branch',
        data1: 'Austin Branch',           
        label2: 'Guarantor',
        data2: 'Jim Robets',
    },    
    {
        rowId: 'primary10',
        label1: 'Loan Officer',
        data1: 'Paul Adams',           
        label2: 'Facility Control Number',
        data2: '56985785',
    },
    {
        rowId: 'primary12',
        label1: 'Portfolio',
        data1: 'Hold for Investment - Taxable',           
        label2: 'Legal Address',
        data2: '4561, Sam Huston Rd, TX, 78026',
    },
    {
        rowId: 'primary13',
        label1: 'Loan Pricing Option',
        data1: 'FC001',           
        label2: 'Facility Current Commitment',
        data2: '$75,000.00',
    },
    {
        rowId: 'primary14',
        label1: 'Base Rate',
        data1: '3.81%',           
        label2: 'Loan Term',
        data2: '360',
    },
    {
        rowId: 'primary15',
        label1: 'Borrower/Loan Spread',
        data1: '7.30%',           
        label2: 'Original Balance',
        data2: '$1,250.00',
    },
    {
		rowId: 'primary15',
        label1: 'Rate Basis',
        data1: 'Actual/365/366',           
        label2: 'End of Prior Year Principal Balance',
        data2: '$23,152.54',        
    },
    {
        rowId: 'primary16',
        label1: 'Loan Effective Date',
        data1: 'Saturday, July 1, 2023',           
        label2: 'Preferred Remittance Instruction',
        data2: 'Text line', 
    },
    {
        rowId: 'primary17',
        label1: 'YTD Interest Paid',
        data1: '$58,000.00',           
        label2: 'PY Interest Paid',
        data2: '$87.37', 
    },
    {
		rowId: 'primary1',
        label1: 'Customer Legal Name',
        data1: 'Sri Rama',           
        label2: 'Inquire Date Time',
        data2: 'Tuesday, December 19,2023',
    },
    {
        rowId: 'primary2',
        label1: 'Loan Alias',
        data1: '610226001',           
        label2: 'Current Balance',
        data2: '$23,152.54',
    },
    {
        rowId: 'primary3',
        label1: 'All-In Rate',
        data1: '11.11%',           
        label2: 'CProjected Loan Maturity Date',
        data2: '45108',
    },
    {
       rowId: 'primary4',
        label1: 'Loan Maturity Date',
        data1: 'Saturday, July 1, 2023',           
        label2: 'Available to Draw',
        data2: '$51847.46',
    },
    {
        rowId: 'primary5',
        label1: 'Est # of Payments Remaining',
        data1: '$455,646',           
        label2: 'Repricing Date',
        data2: 'Saturday, July 1, 2023',
    },
    {
       rowId: 'primary6',
        label1: 'Loan Frequency',
        data1: 'Annually',           
        label2: 'Performing Status',
        data2: 'ACCR',
    },
    {
        rowId: 'primary7',
        label1: 'Accrued Interest',
        data1: '$1,063.68',           
        label2: 'Facility Type',
        data2: 'Revol',
    },
    {
        rowId: 'primary8',
        label1: 'Other Borrowers',
        data1: 'DUCOTE TAMMY 001-7519',           
        label2: 'Facility Original Commitment',
        data2: '$75,000.00',
    },
    {
        rowId: 'primary9',
        label1: 'Branch',
        data1: 'Austin Branch',           
        label2: 'Guarantor',
        data2: 'Jim Robets',
    },    
    {
        rowId: 'primary10',
        label1: 'Loan Officer',
        data1: 'Paul Adams',           
        label2: 'Facility Control Number',
        data2: '56985785',
    },
    {
        rowId: 'primary12',
        label1: 'Portfolio',
        data1: 'Hold for Investment - Taxable',           
        label2: 'Legal Address',
        data2: '4561, Sam Huston Rd, TX, 78026',
    },
    {
        rowId: 'primary13',
        label1: 'Loan Pricing Option',
        data1: 'FC001',           
        label2: 'Facility Current Commitment',
        data2: '$75,000.00',
    },
    {
        rowId: 'primary14',
        label1: 'Base Rate',
        data1: '3.81%',           
        label2: 'Loan Term',
        data2: '360',
    },
    {
        rowId: 'primary15',
        label1: 'Borrower/Loan Spread',
        data1: '7.30%',           
        label2: 'Original Balance',
        data2: '$1,250.00',
    },
    {
		rowId: 'primary15',
        label1: 'Rate Basis',
        data1: 'Actual/365/366',           
        label2: 'End of Prior Year Principal Balance',
        data2: '$23,152.54',        
    },
    {
        rowId: 'primary16',
        label1: 'Loan Effective Date',
        data1: 'Saturday, July 1, 2023',           
        label2: 'Preferred Remittance Instruction',
        data2: 'Text line', 
    },
    {
        rowId: 'primary17',
        label1: 'YTD Interest Paid',
        data1: '$58,000.00',           
        label2: 'PY Interest Paid',
        data2: '$87.37', 
    },

    
]